### ISSUE TITLE
Unable to input negative values in the configurator

### ISSUE THREAD

**Issue by CmdrFluffy** [crazysnailboy/ArmorStand#1]
I am able to open the GUI, and add positive values, but I cannot seem to add negative values, I have tried every key on my keyboard that would be valid for a "-" symbol, and nothing allows me to do it

**Comment by crazysnailboy** [comment]
Hi, thanks for the feedback :) I'll change this in the next version so that negative numbers can be entered, and get automatically converted to their positive counterparts (the valid values for the fields are between 0 and 360).

**Comment by crazysnailboy** [comment]
I've uploaded v1.0.3, which includes the ability to use negative numbers in the text fields.

https://minecraft.curseforge.com/projects/armor-stand-configurator/files
