### ISSUE TITLE
Suggestion: Allow keybind change

### ISSUE THREAD

**Issue by ulkunderscore** [crazysnailboy/ArmorStand#2]
Shift-clicking the armor stand overrides both Quark's and Cyclic's feature to swap all armor at once. It would be helpful to add a config option for alt/opt or ctrl or turn it into an ingame keybind.

**Comment by crazysnailboy** [comment]
I've uploaded v1.0.3, which includes a configurable keybinding for opening the GUI. The chosen key should be held down while clicking the armor stand to display the GUI.

https://minecraft.curseforge.com/projects/armor-stand-configurator/files
